(function() {var implementors = {};
implementors["input_linux_sys"] = ["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"struct\" href=\"input_linux_sys/struct.ff_effect_union.html\" title=\"struct input_linux_sys::ff_effect_union\">ff_effect_union</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"struct\" href=\"input_linux_sys/struct.repeat_settings.html\" title=\"struct input_linux_sys::repeat_settings\">repeat_settings</a>","impl&lt;T:&nbsp;<a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> + ?<a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Sized.html\" title=\"trait core::marker::Sized\">Sized</a>&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"struct\" href=\"input_linux_sys/struct.input_mt_request_layout.html\" title=\"struct input_linux_sys::input_mt_request_layout\">input_mt_request_layout</a>&lt;T&gt;","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"struct\" href=\"input_linux_sys/struct.uinput_ff_upload.html\" title=\"struct input_linux_sys::uinput_ff_upload\">uinput_ff_upload</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"struct\" href=\"input_linux_sys/struct.uinput_ff_erase.html\" title=\"struct input_linux_sys::uinput_ff_erase\">uinput_ff_erase</a>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
